version: '3.7'
services:
  backend:
    image: dextercdalogdog/test-core:dev
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    environment:
      - TZ=Asia/Manila
    networks:
      - redisnet
    expose:
      - 6379
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    environment:
      - TZ=Asia/Manila
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - prometheus:/etc/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 7070:3000
    restart: unless-stopped
    environment:
      - TZ=Asia/Manila
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - grafana:/etc/grafana/provisioning/datasources
  proxy:
    container_name: nginx-proxy
    build: proxy
    environment:
      - TZ=Asia/Manila
    ports:
      - 80:80
    depends_on: 
      - backend
volumes:
  grafana:
  prometheus:
networks:
  redisnet: